name: Daily Message

on:
  schedule:
    - cron: '0 0 * * *'  # Set the time you want the workflow to run (midnight)
  workflow_dispatch: {}  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Write Daily Message
        run: |
          # Import necessary libraries
          from datetime import datetime

          # Define the message
          message = f"Today's date is {datetime.now().strftime('%Y-%m-%d')}... Stay tuned, launching soon."

          # Write the message to the file
          with open('daily_message.txt', 'w') as file:
              file.write(message)

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add daily_message.txt
          git commit -m "Update daily message [skip ci]"
          git push
