name: Write Daily Message

on:
  schedule:
    - cron: '0 0 * * *' # Run the workflow at midnight every day
  workflow_dispatch: {}  # Allow manual triggering

jobs:
  write_message:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the current repository
        uses: actions/checkout@v3

      - name: Create the posts directory
        run: mkdir -p posts

      - name: Get the current date
        run: |
          date=$(date +'%Y-%m-%d')

      - name: Generate the daily message
        run: echo "Today's date is ${date}...Stay tuned launching soon" > "posts/${date}.txt"

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git add posts/*
          git commit -m "Update daily message [skip ci]"
          git push



