name: Write Daily Message

on:
  schedule:
    - cron: '0 0 * * *' # Run the workflow at midnight every day
  workflow_dispatch: {}  # Allow manual triggering

jobs:
  write_message:
    runs-on: ubuntu-latest

    steps:
      - name: Create the posts directory
        run: mkdir -p posts

      - name: Get the current date
        run: |
          date=$(date +'%Y-%m-%d')

      - name: Generate the daily message
        run: echo "Today's date is ${date}...Stay tuned launching soon" > posts/${date}.txt

      - name: Commit the daily message
        run: git add posts/${date}.txt && git commit -m "Update daily message"

      - name: Push the changes to GitHub
        run: git push origin main
